version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: Create_PostgreSQL_1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1080Zxc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
