version: '3'

services:
  web:
    build: .
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./web:/usr/src/Online_Store  

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: Create_PostgreSQL_1
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1080Zxc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"

volumes:
  postgres_data:
